import type { SiteLocale } from "@/lib/preferences";

export const accountCopy = {
  th: {
    login: { back:"กลับหน้าหลัก", kicker:"WELCOME PLAYER", heading:"เข้าสู่ระบบ", intro:"เลือกบัญชีที่คุณต้องการใช้กับ Me Guild", pitch:"ล็อกอินครั้งเดียวเพื่อเข้าถึงปาร์ตี้ กิลด์ กิจกรรม และผลงานทั้งหมดของคุณ", benefits:["ค้นหาปาร์ตี้ที่เข้ากับเวลาและสไตล์ของคุณ","เชื่อม Discord และเข้าห้องเสียงได้รวดเร็ว","สร้าง Portfolio จากกิจกรรมที่เกิดขึ้นจริง"], error:"ไม่สามารถเข้าสู่ระบบได้ กรุณาตรวจสอบการตั้งค่า OAuth หรือลองใหม่อีกครั้ง", secure:"การเข้าถึงที่ปลอดภัย", privacy:"เรารับข้อมูลพื้นฐานจากผู้ให้บริการเพื่อสร้างโปรไฟล์เท่านั้น และจะไม่โพสต์หรือส่งข้อความแทนคุณ", consent:"การดำเนินการต่อหมายถึงคุณยอมรับ", terms:"ข้อกำหนด", policy:"นโยบายความเป็นส่วนตัว", google:"ดำเนินการต่อด้วย Google", discord:"ดำเนินการต่อด้วย Discord" },
    member: { welcome:"ยินดีต้อนรับ", intro:"เลือกภารกิจแรก แล้วเริ่มสร้างเรื่องราวของคุณได้เลย", community:"ดูหน้า Community", quest:"ภารกิจเริ่มต้น", questTitle:"เตรียมโปรไฟล์ให้พร้อมออกทีม", progress:"สำเร็จ 1 จาก 3 ขั้นตอน", tasks:[["เชื่อมบัญชี","สำเร็จ"],["เลือกเกม 3 เกม","ทำต่อ"],["เข้ากิลด์แรก","รออยู่"]], status:"สถานะผู้เล่น", actions:[["หาปาร์ตี้","ดูห้องที่กำลังเปิด"],["ค้นหากิลด์","เจอบ้านที่เข้ากับคุณ"],["กิจกรรม","วางแผนสัปดาห์นี้"],["แต่งโปรไฟล์","ธีม เพลง รางวัล และสิ่งที่ชอบ"]], notice:"Member Hub ระยะที่ 1 — ข้อมูลปาร์ตี้ กิลด์ และกิจกรรมจริงจะต่อผ่าน API กลางในขั้นถัดไป", signOut:"ออกจากระบบ" },
  },
  zh: {
    login: { back:"返回首页", kicker:"欢迎，玩家", heading:"登录", intro:"选择用于 Me Guild 的账号", pitch:"一次登录，即可进入你的队伍、公会、活动和全部玩家履历。", benefits:["找到符合时间与玩法的队伍","连接 Discord，快速加入语音","把真实活动整理成玩家履历"], error:"登录失败，请检查 OAuth 设置或重试。", secure:"安全访问", privacy:"我们只读取创建主页所需的基础资料，不会代表你发帖或发送消息。", consent:"继续即表示你同意", terms:"服务条款", policy:"隐私政策", google:"使用 Google 继续", discord:"使用 Discord 继续" },
    member: { welcome:"欢迎回来", intro:"选择第一个任务，开始书写你的玩家故事。", community:"查看社区", quest:"新手任务", questTitle:"完善主页，准备组队", progress:"已完成 3 步中的 1 步", tasks:[["连接账号","完成"],["选择 3 款游戏","继续"],["加入第一个公会","等待中"]], status:"玩家状态", actions:[["寻找队伍","查看正在招募的房间"],["发现公会","找到适合你的归属"],["活动","安排本周计划"],["装扮主页","主题、音乐、成就与喜好"]], notice:"这是第一阶段会员中心；实时队伍、公会和活动数据将在下一阶段接入共享 API。", signOut:"退出登录" },
  },
  en: {
    login: { back:"Back home", kicker:"WELCOME PLAYER", heading:"Sign in", intro:"Choose the account you want to use with Me Guild", pitch:"One sign-in gives you access to your parties, guilds, events, and complete player story.", benefits:["Find parties that fit your time and play style","Connect Discord and reach voice rooms quickly","Build a portfolio from real activity"], error:"We could not sign you in. Check the OAuth configuration or try again.", secure:"Secure access", privacy:"We only use basic provider information to create your profile. We never post or message on your behalf.", consent:"By continuing, you agree to the", terms:"Terms", policy:"Privacy Policy", google:"Continue with Google", discord:"Continue with Discord" },
    member: { welcome:"Welcome back", intro:"Choose your first quest and start building your story.", community:"View community", quest:"Onboarding quest", questTitle:"Get your profile party-ready", progress:"1 of 3 steps complete", tasks:[["Connect account","Complete"],["Choose 3 games","Continue"],["Join your first guild","Waiting"]], status:"Player status", actions:[["Find a party","See rooms that are open now"],["Discover guilds","Find a community that fits"],["Events","Plan your week"],["Profile Studio","Themes, music, awards, and favorites"]], notice:"This is Member Hub phase one. Live party, guild, and event data will connect through the shared API next.", signOut:"Sign out" },
  },
  ja: {
    login: { back:"ホームへ戻る", kicker:"WELCOME PLAYER", heading:"ログイン", intro:"Me Guild で使うアカウントを選んでください", pitch:"一度のログインで、パーティー、ギルド、イベント、すべての実績にアクセスできます。", benefits:["時間とプレイスタイルに合うパーティーを検索","Discord と連携してすぐにボイスへ参加","実際の活動からポートフォリオを作成"], error:"ログインできませんでした。OAuth 設定を確認するか、もう一度お試しください。", secure:"安全なアクセス", privacy:"プロフィール作成に必要な基本情報のみを使用し、代わりに投稿やメッセージ送信は行いません。", consent:"続行すると、次に同意したことになります：", terms:"利用規約", policy:"プライバシーポリシー", google:"Google で続行", discord:"Discord で続行" },
    member: { welcome:"おかえりなさい", intro:"最初のクエストを選んで、あなたの物語を始めよう。", community:"コミュニティを見る", quest:"スタートクエスト", questTitle:"プロフィールを整えてパーティーへ", progress:"3ステップ中1つ完了", tasks:[["アカウント連携","完了"],["ゲームを3つ選ぶ","続ける"],["最初のギルドに参加","待機中"]], status:"プレイヤーステータス", actions:[["パーティーを探す","募集中のルームを見る"],["ギルドを探す","自分に合う居場所を見つける"],["イベント","今週の予定を立てる"],["プロフィール編集","テーマ・音楽・実績・好きなもの"]], notice:"これはメンバーハブの第1段階です。パーティー、ギルド、イベントのライブデータは次に共通 API へ接続します。", signOut:"ログアウト" },
  },
} satisfies Record<SiteLocale, { login: Record<string, string | string[]>; member: Record<string, string | string[][]> }>;
